#!/bin/bash
echo ""
echo "This script copies a udev rule to /etc to facilitate bringing"
echo "up the ps4eye as /dev/video?."
echo ""
# sudo cp `rospack find ps4eye`/91-ps4eye.rules /etc/udev/rules.d
init_script=`rospack find ps4eye`/script/ps4eye_init.py
sudo cp `rospack find ps4eye`/91-ps4eye.rules /etc/udev/rules.d
sudo sed -i -e "s|INIT_SCRIPT|${init_script}|g" /etc/udev/rules.d/91-ps4eye.rules
echo ""
echo "Restarting udev"
echo ""
sudo service udev reload
sudo service udev restart
